Fix travis-ci setup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,42 +1,57 @@
-language: haskell
+# Use new container infrastructure to enable caching
+sudo: false
 
-env:
-  - GHCVER=8.0.2
-  - GHCVER=8.2.2
-  - GHCVER=8.4.1
-  - GHCVER=head
+# Do not choose a language; we provide our own build tools.
+language: generic
 
 matrix:
+  include:
+    - env: GHCVER=8.0.2 CABALVER=1.24
+      compiler: ": #cabal 8.0.2"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
+    - env: GHCVER=8.2.2 CABALVER=1.24
+      compiler: ": #cabal 8.2.2"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.2], sources: [hvr-ghc]}}
+    - env: GHCVER=8.4.3 CABALVER=1.24
+      compiler: ": #cabal 8.4.3"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.4.3], sources: [hvr-ghc]}}
+    - env: GHCVER=8.6.1 CABALVER=1.24
+      compiler: ": #cabal 8.6.1"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.6.1], sources: [hvr-ghc]}}
+    - env: GHCVER=head CABALVER=head
+      compiler: ": #cabal HEAD"
+      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
+
   allow_failures:
-    - env: GHCVER=head
+   - env: GHCVER=8.6.1 CABALVER=1.24
+   - env: GHCVER=head CABALVER=head
 
 before_install:
-  # If $GHCVER is the one travis has, don't bother reinstalling it.
-  # We can also have faster builds by installing some libraries with
-  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
-  # with cabal-1.18.
   - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
   - travis_retry sudo apt-get update
-  - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
-  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH
+  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
   # Uncomment whenever hackage is down.
   # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
   - cabal update
 
-  # Update happy when building with GHC head
-  - |
-    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
-      cabal install --constraint=transformers\ installed happy alex
-      export PATH=$HOME/.cabal/bin:$PATH
-    fi
-
 install:
-  - cabal install --dependencies-only --enable-tests
-  - cabal configure --enable-tests $MODE
+  - cabal --version
+  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - travis_retry cabal update
+  - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
-  - cabal build
-  - cabal test --show-details=always
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
-  # run cabal package checks.
-  - cabal check
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
